name: bloc_lens
description: Lenses and extensions based on lens_base, made for the bloc package.
version: 0.2.0
repository: https://github.com/leancodepl/bloc_lens
homepage: https://github.com/leancodepl/bloc_lens/tree/main/packages/bloc_lens

environment:
  sdk: ^3.4.3

dependencies:
  bloc: ^8.1.4
  lens_base: ^0.2.0
  meta: ^1.12.0

dev_dependencies:
  leancode_lint: ^13.0.0
