name: lens_base
description: Functional lenses for Dart. Get and set values, even in nested structures.
version: 0.2.0
repository: https://github.com/leancodepl/bloc_lens
homepage: https://github.com/leancodepl/bloc_lens/tree/main/packages/lens_base
topics:
  - dart
  - state
  - state-management

environment:
  sdk: ^3.3.3

dev_dependencies:
  leancode_lint: ^13.0.0
