name: bloc_lens_macros
description: Macros for bloc_lens
version: 0.1.0-dev.1
repository: https://github.com/leancodepl/bloc_lens
homepage: https://github.com/leancodepl/bloc_lens/tree/main/packages/bloc_lens_macros

environment:
  sdk: 3.5.0-234.0.dev

dependencies:
  bloc: ^8.1.4
  bloc_lens: ^0.1.0
  collection: ^1.18.0
  macros: ^0.1.2-main.0
  meta: ^1.15.0

dev_dependencies:
  leancode_lint: ^12.1.0
